name: Deploy Azure Arm

on:

  push:
    branches: 
    - main

  workflow_dispatch:

jobs:

  deploy-arm:

    runs-on: ubuntu-latest

    env:
      RG_NAME: ntier-app-rg
      REGION: East US

    steps:

      - uses: actions/checkout@v2
        name: Checkout

      - uses: azure/login@v1
        name: Azure login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        name: Deploy resource group
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: subscription
          region: ${{ env.REGION }}
          template: rg.template.json
          parameters: rgName=${{ env.RG_NAME }}
          deploymentName: resource-group

      - uses: azure/arm-deploy@v1
        name: Deploy network
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: network.template.json
          parameters: network.parameters.json
          deploymentName: network

      - uses: azure/arm-deploy@v1
        name: Deploy public load balancer
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: public-load-balancer.template.json
          parameters: public-load-balancer.parameters.json
          deploymentName: public-load-balancer          

      - uses: azure/arm-deploy@v1
        name: Deploy web vms
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: webvm.template.json
          parameters: web-vm1.parameters.json vmUsername=${{secrets.AZURE_VM_USERNAME}} vmPassword=${{ secrets.AZURE_VM_PASSWORD }}
          deploymentName: web-vm1

      # - uses: azure/arm-deploy@v1
      #   name: Deploy Web VM 2
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     resourceGroupName: ${{ env.RG_NAME }}
      #     template: webvm.template.json
      #     parameters: web-vm2.parameters.json
      #     deploymentName: web-vm2

      - uses: azure/arm-deploy@v1
        name: Deploy bastion
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: bastion.template.json
          parameters: bastion.parameters.json
          deploymentName: bastion
