name: Deploy Azure Arm

on:
  workflow_dispatch:

jobs:

  deploy-arm:

    runs-on: ubuntu-latest

    env:
      RG_NAME: ntier-app-rg

    steps:

      - uses: actions/checkout@v2
        name: Checkout

      - uses: azure/login@v1
        name: Azure login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        name: Deploy vNet, Sub Nets and NSGs
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: network.template.json
          parameters: network.parameters.json
          deploymentName: network

      - uses: azure/arm-deploy@v1
        name: Deploy Web VM 1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: webvm.template.json
          parameters: web-vm1.parameters.json
          deploymentName: web-vm1

      - uses: azure/arm-deploy@v1
        name: Deploy Web VM 2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: webvm.template.json
          parameters: web-vm2.parameters.json
          deploymentName: web-vm2
